# Non Graded Challenge 4

In [1]:
# import Library

import numpy as np

# Soal

1. Buat Vector dengan python

In [15]:
a = [17, 22, 19]
vect_a = np.array(a)
vect_a 

array([17, 22, 19])

2. Diberikan 3 buah vektor 3 dimensi: $$ A= \begin{bmatrix} 17 \ 22 \ 19 \end{bmatrix} ,B= \begin{bmatrix} 10 \ 20 \ 11 \end{bmatrix}, C= \begin{bmatrix} 5 \ 12 \ 9 \end{bmatrix} $$
Hitunglah:
*   A+B
*   B-C
*   A dot C
*   A x B
*   norm A
*   Sudut antara vektor A dan B



In [19]:
b = [10, 20, 11]
vect_b = np.array(b)
print(vect_b)

c = [5, 12, 9]
vect_c = np.array(c)
print(vect_c)

[10 20 11]
[ 5 12  9]


In [ ]:
b = [[10],
     [20],
     [19]]

c = [[5],
     [12],
     [9]]     

matrix_b = np.array(b)
print(matrix_b)
print('')

matrix_c = np.array(c)
print(matrix_c)
print('')

In [20]:
# hitung a+b

print(vect_a + vect_b)

[27 42 30]


In [21]:
# hitung b-c

print(vect_b - vect_c)

[5 8 2]


In [22]:
# A dot C

print(vect_a @ vect_c)

520


In [24]:
# A x B

print(vect_a * vect_b)

[170 440 209]


In [26]:
# norm A

print(np.linalg.norm(vect_a))

33.67491648096547


In [29]:
# Sudut antara vektor A dan B

cos_theta = (vect_a @ vect_b) / (np.linalg.norm(vect_a) * np.linalg.norm(vect_b))
print('Cosine Similarity : ', cos_theta)

radian = np.arccos(cos_theta)
degree = np.degrees(radian)

print('Radian : ', radian)
print('Degree : ', degree)

Cosine Similarity :  0.9759590023331435
Radian :  0.21971776576153962
Degree :  12.588900662180242
