# FTDS //NONGRADEDCHALLENGE 5

1. Buatlah Tensor dibawah ini dengan Python:

  
  
  
 
 

2. Lakukan perkalian terhadap matrix berikut:

$$ A = \begin{bmatrix} 23 & 50 & 19 \ 7 & 12 & 109 \ 57 & 67 & 98 \end{bmatrix} \begin{bmatrix} 17 \ 22 \ 19 \end{bmatrix} $$

Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:

$$ \begin{bmatrix} 23 & 50 & 19 \ 7 & 12 & 109 \ 57 & 67 & 98 \end{bmatrix} $$

In [1]:
import numpy as np

In [18]:
# 1. Memanggil tensor

a = ([ 
    [[23, 50], [57, 67]], 
    [[7, 12], [99, 43]],                 
    [[75, 21], [87, 26]],
    [[57, 12], [18, 84]],
    ])

matrix_a = np.array(a)
print(matrix_a)

[[[23 50]
  [57 67]]

 [[ 7 12]
  [99 43]]

 [[75 21]
  [87 26]]

 [[57 12]
  [18 84]]]


In [24]:
# 2. Perkalian Matrix

A = [[23, 50, 19],
     [7, 12, 109],
     [57, 67, 98]]

B = [[17],
     [22],
     [19]]

matrix_A = np.array(A)
matrix_B = np.array(B)

print(matrix_A @ matrix_B)

[[1852]
 [2454]
 [4305]]
